[build]
  command = "npm install --legacy-peer-deps && NEXT_TELEMETRY_DISABLED=1 NODE_OPTIONS='--openssl-legacy-provider --max-old-space-size=4096' npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--openssl-legacy-provider --max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"
  # Force npm usage instead of yarn
  NETLIFY_USE_YARN = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  condition = "not_static"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"